environment:
  nodejs_version: "7"
cache:
 - "%LOCALAPPDATA%\\Yarn"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn
test_script:
  - bin\run version
  - bin\run help

build: off
