---
version: 2
executorType: docker
containerInfo:
  - image: dickeyxxx/cli-engine-docker:v1.2.0-node7
stages:
  build:
    workDir: ~/cli
    steps:
      - type: checkout
      - type: cache-restore
        key: cli
      - type: shell
        command: |
          set -exu
          yarn config set registry https://cli-npm.heroku.com
          yarn
          ./bin/run version
          ./bin/run help
      - type: cache-save
        key: cli
        paths:
          - /usr/local/share/.cache/yarn
      - type: deploy
        shell: /bin/bash
        command: |
          set -e
          gpg --passphrase $HEROKU_WINDOWS_SIGNING_PASS -d resources/deb/key.gpg | gpg --import
          set -ex
          TAG=`git describe --exact-match HEAD || echo NOTAG`
          if [ "${TAG}" != "NOTAG" ]; then
            yarn run release stable
            ./scripts/release-deb stable
          fi
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            yarn run release beta
            ./scripts/release-deb beta
          fi
          if [ "${CIRCLE_BRANCH}" == "deb" ]; then
            yarn run release dev
            ./scripts/release-deb dev
          fi
