---
version: 2
executorType: docker
containerInfo:
  - image: dickeyxxx/cli@sha256:e7de56db77c9711fa72844d708a0e0f1d453ca23e3548d69b50800521fd36bd9
stages:
  build:
    workDir: ~/src/github.com/heroku/cli
    steps:
      - type: checkout
      - type: cache-restore
        key: heroku-cli-v5
      - type: shell
        command: |
          set -exu
          export PATH=~/bin:$PATH
          go get -u github.com/alecthomas/gometalinter
          gometalinter --install
          ./bin/test -v -race -cover -coverprofile=coverage.out -ginkgo.v
          make test -j 6
          ./bin/run version
          ./bin/run help
          ./bin/lint
      - type: cache-save
        key: heroku-cli-v5
        paths:
          - ~/src/github.com/heroku/cli/tmp/cache
          - ~/bin
      - type: deploy
        shell: /bin/bash
        command: |
          set -eu
          echo $HEROKU_WINDOWS_SIGNING_PASS | gpg --passphrase-fd 0 --batch --yes -d resources/deb/key.gpg | gpg --import || echo "no passphrase"
          echo $HEROKU_WINDOWS_SIGNING_PASS | gpg --batch --yes --passphrase-fd 0 -o resources/exe/heroku-codesign-cert.pfx -d resources/exe/heroku-codesign-cert.pfx.gpg
          if [ `git name-rev --name-only --tags HEAD` != "undefined" ]; then
            CHANNEL=stable make release -j6
          fi
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            CHANNEL=beta make release -j6
          fi
          if [ "${CIRCLE_BRANCH}" == "circle-2.0" ]; then
            CHANNEL=beta make release -j6
          fi
