---
version: 2
executorType: docker
containerInfo:
  - image: dickeyxxx/cli-engine-docker:v1.0.1
stages:
  build:
    workDir: ~/cli
    steps:
      - type: checkout
      - type: cache-restore
        key: cli
      - run: yarn
      # only needed for dev builds that reference git SHAs instead of npm packages
      # because prepare step is not run
      - run: cd node_modules/cli-engine && yarn
      - run: ./bin/run version
      - run: ./bin/run help
      - type: cache-save
        key: cli
        paths:
          - /usr/local/share/.cache/yarn
      - type: deploy
        shell: /bin/bash
        command: |
          set -exu
          TAG=`git describe --exact-match HEAD || echo NOTAG`
          if [ "${TAG}" != "NOTAG" ]; then
            yarn run release stable
          fi
          if [ "${CIRCLE_BRANCH}" == "v6" ]; then
            yarn run release beta
          fi
          if [ "${CIRCLE_BRANCH}" == "dev" ]; then
            yarn run release dev
          fi
          if [ "${CIRCLE_BRANCH}" == "dev2" ]; then
            yarn run release dev2
          fi
