---
version: 2
jobs:
  build:
    working_directory: ~/cli
    docker:
      - image: dickeyxxx/cli-engine-docker:v1.2.1-node7
    steps:
      - checkout
  test:
    steps:
      - run: echo test
  deploy:
    steps:
      - run: echo deploy
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test
      - deploy
# stages:
#   build:
#     steps:
#       - checkout
#       - restore_cache:
#           keys:
#             - cli
#       - run: |
#           set -exu
#           yarn config set registry https://cli-npm.heroku.com
#           yarn
#           ./bin/run version
#           ./bin/run help
#       - save_cache:
#           key: cli
#           paths:
#             - /usr/local/share/.cache/yarn
#       - type: deploy
#         shell: /bin/bash
#         command: |
#           set -e
#           echo $HEROKU_DEB_KEY | base64 -d | gpg --import
#           set -ex
#           TAG=`git describe --exact-match HEAD || echo NOTAG`
#           if [ "${TAG}" != "NOTAG" ]; then
#             yarn run release stable
#             ./scripts/release-deb stable
#           elif [ "${CIRCLE_BRANCH}" == "master" ]; then
#             yarn run release beta
#             ./scripts/release-deb beta
#           elif [ "${CIRCLE_BRANCH}" == "dev" ]; then
#             yarn run release dev
#             ./scripts/release-deb dev
#           fi
