---
version: 2
executorType: docker
jobs:
  build:
    workDir: ~/cli
    docker:
     - image: dickeyxxx/cli-engine-docker:v1.3.1
    steps:
      - type: checkout
      - type: cache-restore
        key: cli
      - type: shell
        command: |
          set -exu
          yarn config set registry https://cli-npm.heroku.com
          yarn install --pure-lockfile
          yarn check
          # build dev only if it is a git checkout
          if [ "${CIRCLE_BRANCH}" == "dev" ] && \
             [ ! -d ~/cli/node_modules/cli-engine/lib ]; then
            cd ~/cli/node_modules/cli-engine && yarn && cd ~/cli
          fi
          ./bin/run version
          ./bin/run help
      - type: cache-save
        key: cli
        paths:
          - /usr/local/share/.cache/yarn
      - type: deploy
        shell: /bin/bash
        command: |
          set -e
          echo $HEROKU_DEB_KEY | base64 -d | gpg --import
          set -ex
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            TAG=`git describe --exact-match HEAD || echo NOTAG`
            if [ "${TAG}" != "NOTAG" ]; then
              yarn run release stable
              ./scripts/release-deb stable
            else
              yarn run release beta
              ./scripts/release-deb beta
            fi
          elif [ "${CIRCLE_BRANCH}" == "dev" ]; then
            yarn run release dev
            ./scripts/release-deb dev
          fi
      - persist_to_workspace:
          root: .

  build_osslsigncode:
    working_directory: /tmp
    docker:
      - image: dickeyxxx/cli-engine-docker:v1.3.1
    steps:
      - run: |
          if [ ! -d ~/osslsigncode ]; then
            wget https://cli-assets.heroku.com/osslsigncode-1.7.1.tar.gz &&
            tar -xvzf osslsigncode-1.7.1.tar.gz &&
            mv osslsigncode-1.7.1 ~/osslsigncode &&
            cd ~/osslsigncode && ./configure && make
          fi
      - save_cache:
          key: osslsigncode
          paths:
            - ~/osslsigncode
  release_windows:
    working_directory: ~/cli
    docker:
      - image: dickeyxxx/cli-engine-docker:v1.3.1
    steps:
      - attach_workspace:
          at:  ~/cli
      - restore_cache:
          keys:
            - osslsigncode
      - run: find ~/cli && find ~/osslsigncode
      - type: shell
  echo2:
    working_directory: ~/echo1
    docker:
      - image: dickeyxxx/cli-engine-docker:v1.3.1
    steps:
      - run: echo 2
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - build_osslsigncode
      - release_windows:
          requires:
            - build
            - build_osslsigncode
      - echo2
