---
version: 2
executorType: docker
jobs:
  build:
    workDir: ~/cli
    docker:
     - image: dickeyxxx/cli-engine-docker:v1.3.1
    steps:
      - type: checkout
      - type: cache-restore
        key: cli
      - type: shell
        command: |
          set -exu
          yarn config set registry https://cli-npm.heroku.com
          yarn install --pure-lockfile
          yarn check
          # build dev only if it is a git checkout
          if [ "${CIRCLE_BRANCH}" == "dev" ] && \
             [ ! -d ~/cli/node_modules/cli-engine/lib ]; then
            cd ~/cli/node_modules/cli-engine && yarn && cd ~/cli
          fi
          ./bin/run version
          ./bin/run help
      - type: cache-save
        key: cli
        paths:
          - /usr/local/share/.cache/yarn
      - type: deploy
        shell: /bin/bash
        command: |
          set -e
          echo $HEROKU_DEB_KEY | base64 -d | gpg --import
          set -ex
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            TAG=`git describe --exact-match HEAD || echo NOTAG`
            if [ "${TAG}" != "NOTAG" ]; then
              yarn run release stable
              ./scripts/release-deb stable
            else
              yarn run release beta
              ./scripts/release-deb beta
            fi
          elif [ "${CIRCLE_BRANCH}" == "dev" ]; then
            yarn run release dev
            ./scripts/release-deb dev
          fi
      - persist_to_workspace:
          root: .

  release_windows:
    working_directory: ~/cli
    docker:
      - image: dickeyxxx/cli-engine-docker:v1.3.1
    steps:
      - attach_workspace:
          at:  ~/cli
      - run: find ~/cli
      - type: shell
        command: |
          $(DIST_DIR)/$(VERSION)/heroku-windows-%.exe: tmp/windows-% $(CACHE_DIR)/git/Git-2.8.1-386.exe $(CACHE_DIR)/git/Git-2.8.1-amd64.exe
          @mkdir -p $(@D)
          rm -rf tmp/windows-$*-installer
          cp -r tmp/windows-$* tmp/windows-$*-installer
          cp $(CACHE_DIR)/git/Git-2.8.1-$*.exe tmp/windows-$*-installer/heroku/git.exe
          sed -e "s/!define Version 'VERSION'/!define Version '$(VERSION)'/" resources/exe/heroku.nsi |\
            sed -e "s/InstallDir .*/InstallDir \"\$$PROGRAMFILES$(if $(filter amd64,$*),64,)\\\Heroku\"/" \
            > tmp/windows-$*-installer/heroku/heroku.nsi
          makensis tmp/windows-$*-installer/heroku/heroku.nsi > /dev/null
          @osslsigncode -pkcs12 resources/exe/heroku-codesign-cert.pfx \
            -pass '$(HEROKU_WINDOWS_SIGNING_PASS)' \
            -n 'Heroku CLI' \
            -i https://toolbelt.heroku.com/ \
            -in tmp/windows-$*-installer/heroku/installer.exe -out $@
  echo2:
    working_directory: ~/echo1
    docker:
      - image: dickeyxxx/cli-engine-docker:v1.3.1
    steps:
      - run: echo 2
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - release_windows:
          requires:
            - build
      - echo2
