
name: heroku
version: '6.12.6'
summary: Heroku CLI
description: Heroku CLI
grade: stable
confinement: strict

apps:
    heroku:
        command: bin/heroku
        plugs: [network]

parts:
  hello-node-snap:
    plugin: nodejs
    node-engine: 8.1.3
    node-packages:
      - heroku-cli
